spring.application.name=learn-spring-boot
# application.properties
server.address=0.0.0.0
  # Change this to a different IP if needed
server.port=8081
currency-service.url=http://default.rustyProgrammer.com
currency-service.username=defaultusername
currency-service.key=defaultkey